name: test
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
           systemctl enable --now cockpit.socket
           sudo pm2 stop 0
           pm2 list
           exit
          host: ${{ secrets.HOST }}
          user: flox-vm
          key: ${{ secrets.PRIVATE_KEY }}
          pass: ${{ secrets.PASSWORD }}
