name: test
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: NodeCICD Deployment
        uses: fifsky/ssh-action@master
        with:
          command: |
           systemctl enable --now cockpit.socket
           cd expresscicd
           git pull origin master
           git status
           pm2 restart 0
           exit
          host: ${{ secrets.HOST }}
          user: flox-vm
          key: ${{ secrets.PRIVATE_KEY }}
          pass: ${{ secrets.PASSWORD }}
